springdoc:
  use-management-port: true
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include:
          - openapi
          - swagger-ui
          - beans
  server:
    port: 9090

spring:
  datasource:
    username: root
    password: mypassword
    url: jdbc:mysql://localhost/book_management

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
