springdoc:
  use-management-port: true
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include:
          - openapi
          - swagger-ui
          - beans
  server:
    port: 9090
